services:
  api:
    build: .
    container_name: task_api_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/tasks
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: taskdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - taskdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: task_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  taskdata:
    driver: local
